version: '3.0'
#services are the containers
services:
  angular: 
    build: ./angular
    ports:
      - "4200:4200" 
  express:
    build: ./express
    ports:
      - "3000:3000"
    links:
      - db 
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    